name: Test Couchbase connection
on: [workflow_dispatch]
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://github.com/couchbaselabs/couchbase-shell/releases/download/v0.75.1/cbsh-x86_64-unknown-linux-gnu.tar.gz
      - run: tar -xvzf cbsh-x86_64-unknown-linux-gnu.tar.gz
      - name: Retrieve the secret and decode it to a file
      - env:
          NUSHELL_CONFIG: |
            ${{ secrets.NUSHELL_CONFIG }}
        run: echo "$NUSHELL_CONFIG" > config
      - run: ./cbsh --config-dir . -c cb-env
        shell: bash
