name: Test Couchbase connection
on: [workflow_dispatch]
defaults:
  run:
    shell: cbsh --script {0}

jobs:
  setup:
    runs-on: ubuntu-22.04
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      BUCKET:  ${{ env.BRANCH_NAME }}_${{ env.COUCHBASE_DEFAULT_BUCKET }}
      SCOPE:  ${{ env.BRANCH_NAME }}_${{ env.COUCHBASE_DEFAULT_SCOPE }}
      COLLECTION:  ${{ env.BRANCH_NAME }}_${{ env.COUCHBASE_DEFAULT_COLLECTION }}
    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: ldoguin/setup-cbsh@develop
      with:
        version: 'source'
        enable-plugins: ''
        config:  ${{ secrets.CBSHELL_CONFIG }}
    - name: Setup Couchbase Bucket, Scope, Collection
      run: |
          source ${{ github.workspace }}/scripts/setupTest.nu
          setupTest $env.BUCKET $env.SCOPE $env.COLLECTION
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
          java-version: '17'
          distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Execute Gradle build
      run: ./gradlew build
    - name: Tear Down Bucket
      run: |
        buckets drop $env.BUCKET

