name: Test setup-nu
on: [workflow_dispatch]
defaults:
  run:
    shell: cbsh --script {0}

jobs:
  basic-usage:
    runs-on: ubuntu-22.04
    steps:
    - uses: ldoguin/setup-cbsh@develop
      with:
        version: '*'
        enable-plugins: false
        config:  ${{ secrets.NUSHELL_CONFIG }}
    - run: |
        cb-env
