name: Test setup-nu
on: [workflow_dispatch]
defaults:
  run:
    shell: cbsh --config-dir . --script {0}


jobs:
  basic-usage:
    runs-on: ubuntu-22.04
    steps:
    - uses: ldoguin/setup-cbsh@develop
      with:
        version: '*'
        enable-plugins: false
    - run: echo "$NUSHELL_CONFIG" > config
      env:
        NUSHELL_CONFIG: |
          ${{ secrets.NUSHELL_CONFIG }}
      shell: bash
    - run: |
        cb-env
